// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeyQp3g5kxjtjUh3-5xWoS9QyvLTLl5XI',
    appId: '1:326948012791:web:bf6b073e3823a19dd509f2',
    messagingSenderId: '326948012791',
    projectId: 'kisan-c8d22',
    authDomain: 'kisan-c8d22.firebaseapp.com',
    storageBucket: 'kisan-c8d22.appspot.com',
    measurementId: 'G-2EVQJ5YJG1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3lXizHhSS1XLv5Y7B2xInqbqGIkND8Ek',
    appId: '1:326948012791:android:603b81a64b6dbdd3d509f2',
    messagingSenderId: '326948012791',
    projectId: 'kisan-c8d22',
    storageBucket: 'kisan-c8d22.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdSokI1-a9LnvIZP3JrQwi1RMY-WcM_FU',
    appId: '1:326948012791:ios:25b5ed126b3cd7c3d509f2',
    messagingSenderId: '326948012791',
    projectId: 'kisan-c8d22',
    storageBucket: 'kisan-c8d22.appspot.com',
    iosBundleId: 'com.example.kisan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBdSokI1-a9LnvIZP3JrQwi1RMY-WcM_FU',
    appId: '1:326948012791:ios:37d4d4d74ab6da4bd509f2',
    messagingSenderId: '326948012791',
    projectId: 'kisan-c8d22',
    storageBucket: 'kisan-c8d22.appspot.com',
    iosBundleId: 'com.example.kisan.RunnerTests',
  );
}
